### ISSUE TITLE
Could not resolve dependencies for project

### ISSUE THREAD

**Issue by soaresmarcus** [usnistgov/iheos-toolkit2#124]
I'm having the following error:

Failed to execute goal on project validators-registry-message: Could not resolve dependencies for project gov.nist.toolkit:validators-registry-message:jar:2.202.9: Failure to find gov.nist.toolkit:saml:jar:2.202.0-SNAPSHOT in https://gazelle.ihe.net/nexus/content/repositories/thirdparty was cached in the local repository, resolution will not be reattempted until the update interval of gazelle-3rd-party has elapsed or updates are forced -> [Help 1]

How should I proceed?

**Comment by rmoult01** [comment]
I think that is a problem with some of the repositories that Bill needs to work on. I got around it by adding the saml jar to my local repository manually.


Ralph


________________________________

**Comment by iheos** [comment]
I presume that Ralph has already pointed you to the instructions for
installing the public cert that will get you access to the Nexus system.
This approach has worked for some but not for everybody.  For the short
term I suggest following Ralph's suggestion of installing the saml jar in
your local maven repository.  For the long term we are pursuing two
approaches:  putting up a nexus repository that we manage or debugging the
Gazelle Nexus certificate problem.  I will announce when I have one of
these long-term solutions in place.

**Comment by soaresmarcus** [comment]
Thanks for your quick answer.
Ralph, where can I find the saml jar? I haven't found it on the web.

**Comment by rmoult01** [comment]
Unzip this into your repository in the toolkit directory. For example:


/home/yourUserName/.m2/repository/gov/nist/toolkit


Ralph


________________________________

**Comment by soaresmarcus** [comment]
Problem solved. Thank you!


Marcus
