### ISSUE TITLE
Consider extending codes.xml to add history for each element

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#162]
Today codes.xml has comments in the file that give you an indication of why a block of entries exist, but I think we could do better. Consider adding these attributes (needs a little more thought)

submitter="email address"
date="date"
ref="URL reference"
value_set="value set"
comment="comment"
category="classCode, typeCode, ...."

This would allow me to write a script to go into codes.xml and pull out only the subset of things that I really want and ignore the other things.

Nice to have, not for Jan/Feb 2017

**Comment by stl-steve-moore** [comment]
I added Dave as an assignee. He is doing some background work on this but no code changes yet.

**Comment by iheos** [comment]
Steve and Lynn now maintain this additional information in spreadsheets.
