### ISSUE TITLE
System under test for this Test Session is not sorted

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#170]
![system_under_test_selection](https://cloud.githubusercontent.com/assets/889913/21404356/67ab8126-c786-11e6-830a-edab7ff6ca80.png)

When selecting the system under test, the list presented is not sorted. It would help to have that list sorted either alphabetically or by actor (though by actor is hard). If you sort alphabetically, we will develop naming conventions that will help us group and locate the actor names.

**Comment by iheos** [comment]
Fixed in release 4.2
