### ISSUE TITLE
In WUSTL branch, resetting RIG test environment does not clear logs

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#174]
Specifically, the transaction log for xxxx_ids_e still has a transaction from several days ago, even after I explicitly told the system to re-initialize the simulators.
![rig-environment-01](https://cloud.githubusercontent.com/assets/889913/21509588/13eaa8d6-cc50-11e6-9341-3480dde67703.png)

**Comment by iheos** [comment]
In the non-imaging sims re-initializing deletes the old sims and re-creates
them thus clearing the stored content and logs. Did the imaging sims not
follow this pattern?

**Comment by stl-steve-moore** [comment]
They are supposed to follow that pattern. As I run tests with this particular set of simulators, that is not happening (in our branch).

**Comment by stl-steve-moore** [comment]
It turns out that the IIG simulators are also not refreshed when requested. I will fix that at the same time.
