### ISSUE TITLE
Repository simulator does not send a Register request for Tests 11981, 11983, 11986, and 12369

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#257]
![11986 register bug](https://cloud.githubusercontent.com/assets/2388275/24262115/76be29de-0fcf-11e7-9d67-88acd2c36ce1.PNG)

**Comment by iheos** [comment]
This test is kinda complicated.  The first two sections (submit and submit_uppercase_hash) do result in a Register transaction.  The second pair of sections (submit_bad_hash and submit_bad_size) prove that the Repository catches the errors contained in the transactions and do not send on the Register transaction.  I can see where this is a little weird from a diagramming perspective.

The models you are working from describe the correct operation.  These second two sections are negative test cases where we are breaking things.  The ExpectedStatus is Failure.  

I think the way they are diagramed is correct: Register not found.
