### ISSUE TITLE
Registry Conformance Tests does not respect CP-ITI-949

### ISSUE THREAD

**Issue by Thopap** [usnistgov/iheos-toolkit2#264]
The XDS.b Registry conformace tests submit a folder having:
`<rim:Slot
               name="lastUpdateTime">
            <rim:ValueList>
               <rim:Value>20041224</rim:Value>
            </rim:ValueList>
         </rim:Slot>`

It was defined in CP-ITI-949 that the lastUpdateTime need to have "second" precision. If a registry validate this, this request will fail.

**Comment by iheos** [comment]
This CP has not been integrated into the TF as of revision 13 (2016-09-09).

I have updated the test data but will not update the validators until published in TF.  The code changes have been made to gov.nist.toolkit.valregmetadata.validators.FolderValidator.java, line 145 but are commented out for now.

**Comment by Thopap** [comment]
Hello Bill,
the wrong time format is still present in the testdata of xdstools version 7.1.0. Looking at 4.2.3.4.6 Folder.lastUpdateTime in TF3, the description "The format of the lastUpdateTime value is DTM and shall have at least “second” precision" was already integrated.

Can you please update the testdata (search for [https://github.com/usnistgov/iheos-toolkit2/search?q=lastUpdateTime%3A+20041224&unscoped_q=lastUpdateTime%3A+20041224] show several places)?

Thank you,
Thomas
