### ISSUE TITLE
Repository/Registry simulator cannot be created by hand

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#317]
![no-reg-rep](https://user-images.githubusercontent.com/889913/27202663-11e5190e-51e8-11e7-9b3d-43de5cde67af.png)
![no-reg-rep-2](https://user-images.githubusercontent.com/889913/27202664-11f0ed06-51e8-11e7-9bf7-b4368073dd9e.png)

I saw this on the Sequoia VM and also see it on a branch that I am using.
When I try to create a combined repository/registry by hand, that option is not available to me.

The second screen capture shows that the toolkit still knows about such a combined simulator. When we do the orchestration for testing an IDS, we create that combined simulator under program control.

**Comment by iheos** [comment]
What branch (s) do you know where I can observe this?

**Comment by stl-steve-moore** [comment]
I found this to be true on both the master and develop branches. I pulled them both just now and see the same behavior on both.
