### ISSUE TITLE
Nice to have: Date stamp on a simulator

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#327]
It would be nice if the simulator management page would list the date/time the simulator was created.

Bonus points awarded for a second field that shows the date/time the simulator last responded to any kind of transaction.

I know I can get this by going to the logs.

Slothful Steve

**Comment by skbhaskarla** [comment]
Here's a screenshot of the new Simulator Manager page with the three new features highlighted in yellow.  (Code is on my local branch.)
![new simulator manager](https://user-images.githubusercontent.com/2388275/29233229-de7b1fca-7ebd-11e7-881a-0b44f528bd14.png)
