### ISSUE TITLE
Conformance Test: Profile Tab Needs Work

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#332]
![toolkit-a1](https://user-images.githubusercontent.com/889913/30666866-4723ff98-9e1b-11e7-90e7-5a49ed18d2bf.png)

This is on the develop branch that I pulled 2017.09.20. See screen capture. I selected the tab to test an IIG actor. In the display, it still shows XDS as a testing tab. That should be XCA-I for this actor.

I know this is a works in progress. You might say: Yep, on the list already.

**Comment by skbhaskarla** [comment]
Since the profile type for the IIG actor was not available at that time we defaulted the profile to XDS. I'll change the profile for all imaging actors to XCA-I.
