### ISSUE TITLE
Registry conformance Tests does not invoke TLS endpoints

### ISSUE THREAD

**Issue by Thopap** [usnistgov/iheos-toolkit2#348]
I am using XDS tools 6.0.2 and i have configured my registry (which only has secured / TLS endpoints). 
The basic "FindDocuments" query works without any issue. But if i try to start the conformance tests, the initial test "123456" fails with "gov.nist.toolkit.xdsexception.client.XdsInternalException: No endpoint specified for transaction rb and XDS version XDS.b and secure = false on site CHR", even if TLS checkbox is clicked.

**Comment by iheos** [comment]
Fixed in version 6.2.0
