### ISSUE TITLE
Invalid bundle request (ITI-65) in Document Recipient - XDSonFHIR

### ISSUE THREAD

**Issue by Thopap** [usnistgov/iheos-toolkit2#349]
I have tried the FHIR MHD test provided in (XDStools 6.0.2):
Document Recipient - XDSonFHIR
Test: pdb_rplc_recresp - MHD Document Recipient/Responder Document Replace (text/plain)
--> Section: submit_original --> Step: SendPdb

This ITI-65 request currently fail against our ITI-65 Recipient, because some validation rules prevent the processing:
EVS tools mark the request as invalid:
- https://gazelle.ihe.net/EVSClient/detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.1.2.1.4.846868

At least one constraint from FHIR is not present (https://www.hl7.org/fhir/bundle.html)
- bdl-3 contraint also not present for DocumentManifest and Binary

The MDH specification define that Bundle.meta.profile shall be present for a ITI-65 request.

**Comment by iheos** [comment]
Fixed in version 6.2.0
