### ISSUE TITLE
Feature 2018: Success logs always visible to web user

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#400]
If a conformance test completes successfully today, the user sees the green light but no details of what was tested.

That reduces the noise in the display output (for managers) but might leave technical folks wondering what was actually tested.

Consider adding a report area for that level of detail that can be expanded if the user wants to see it. I like the fact that the display is in your face when there are issues; there is nothing to expand. Maybe that behavior stays. I do want something that is not obtrusive that I can ask for more details.

Couple this with another request for an expandable area for debugging output. That is different from this.

**Comment by iheos** [comment]
Fixed
