### ISSUE TITLE
Feature 2018: Document + Metadata Testing

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#402]
I would like to tell someone to submit a C-CDA History and Physical document. Based on that submission, I want to test at least two things:
1) Content in the document itself that I have given them (current meds).
2) Metadata that is based on the document type. Today we only test that the metadata codes are found in codes.xml. If someone submits a History and Physical, that defines certain metadata values that we could test.

So, I want toolkit to somehow pass control to me so I can do that work and return results to you for management/display.

You mentioned a plugin model. That would be OK with me.

**Comment by iheos** [comment]
I believe the new validator plugin model can be used for this purpose.  If you find it doesn't please reopen the issue.
