### ISSUE TITLE
Feature: Add SSL/TLS icon to each test that is run with TLS enabled

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#409]
You have the checkbox at the top of the test area to enable TLS.

It would be helpful to add an indicator to each test that is actually run with TLS. You already have a mechanism to add "L" for local. You could add another letter or possibly an icon.

Here is a second idea to consider. The checkbox is nice when you run to run all tests in one mode or the other. Today I am debugging TLS. I really want two run buttons on each test. One is the "run with TLS" and the second is "run w/o" TLS. The problem with this idea is that it does not scale very well. Will I ask for another button next week that is run with XUA? How about "run with XUA but not TLS?" So, this second idea may not be advisable.

**Comment by iheos** [comment]
Added "TLS" label to test and section headers. Labeling the test is a little tricky.  What if there are two sections, one run with TLS and the other without?  For now the test is labeled TLS is any section is run with TLS.  This may have to change after we collection more opinions.
