### ISSUE TITLE
Conformance Actor Test statistics not refreshed when re-running the entire test collection

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#441]
This problem was confirmed on the latest Develop branch. (May have been around for a long time.)

A walk-around is to clear the log for the all the tests, using main test bar Delete All Logs icon, and re-running all the tests.

**Comment by iheos** [comment]
Your suggested work-around is good.  The old log files are going to get deleted anyway.  I would suggest programmatically triggering the Delete All Logs as a precondition to Run All. I think this is what you are suggesting.

**Comment by skbhaskarla** [comment]
When the Run All button is clicked, there will be no warning to the user before deleting all the logs.

**Comment by skbhaskarla** [comment]
Fixed.
