### ISSUE TITLE
Bug in test 15817- No response data received 

### ISSUE THREAD

**Issue by agalanr86** [usnistgov/iheos-toolkit2#445]
We found a problem with test 15817, at method getStringFromBufferedReader at class AdtSender.java. This test failed because the response wasempty, but we validate that our server is sending the rigth answer to the client, but the problem is that this method isn´t reading it correctly.

We try this method in an example class and we received the respond,but "while" never ends.

**Comment by iheos** [comment]
Fix applied in release 7.0.1.
