### ISSUE TITLE
HL7V3 in NIST XDS Tool

### ISSUE THREAD

**Issue by rohitcumarpanwar** [usnistgov/iheos-toolkit2#451]
How I can get HL7V3 in NIST XDS Tool? (patient identity feed)

**Comment by iheos** [comment]
HL7V3 patient feed is not implemented in this tool. Depending on what you are trying to accomplish there are alternative approaches. 

If you are working with the Registry simulator, the patient feed tool can send a v2 message.

If you are working with the conformance tool, there is an option to bypass patient feed. In this situation you add the patient identity to your registry manually.

Also I believe the gazelle tools offer a v3 pif.

Bill
