### ISSUE TITLE
Unable to Access transaction Endpoints

### ISSUE THREAD

**Issue by atifumarcloud** [usnistgov/iheos-toolkit2#498]
Hi Guys,
I tried to access these transaction endpoints but these are unable to access, please help?

      <transaction name="sq.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsregistryb</transaction>
      <transaction name="sq.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsregistryb</transaction>
      <transaction name="r.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsregistryb</transaction>
      <transaction name="r.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsregistryb</transaction>
      <transaction name="pr.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsrepositoryb</transaction>
      <transaction name="pr.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsrepositoryb</transaction>
      <repository uid="1.19.6.24.109.42.1.5" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsrepositoryb</repository>
      <repository uid="1.19.6.24.109.42.1.5" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsrepositoryb</repository>
      <home>urn:oid:1.19.6.24.109.42.1.3</home>
      <transaction name="xcq" secure="0">http://ihexds.nist.gov:12080/tf6/services/rg</transaction>
      <transaction name="xcq" secure="1">https://ihexds.nist.gov:12081/tf6/services/rg</transaction>
      <transaction name="xcr" secure="0">http://ihexds.nist.gov:12080/tf6/services/rg</transaction>
      <transaction name="xcr" secure="1">https://ihexds.nist.gov:12081/tf6/services/rg</transaction>
      <transaction name="igq" secure="0">http://ihexds.nist.gov:12080/tf6/services/xcaregistry</transaction>
      <transaction name="igq" secure="1">https://ihexds.nist.gov:12081/tf6/services/xcaregistry</transaction>
      <transaction name="igr" secure="0">http://ihexds.nist.gov:12080/tf6/services/xcarepository</transaction>
      <transaction name="igr" secure="1">https://ihexds.nist.gov:12081/tf6/services/xcarepository</transaction>
      <PidAllocateEndpoint>http://ihexds.nist.gov:12080/xdstools/pidallocate?rest=1</PidAllocateEndpoint>

**Comment by iheos** [comment]
The server linked to ihexds.nist.gov is going through an overhaul and is not available.  I suggest downloading the toolkit and using it locally.

Bill

**Comment by atifumarcloud** [comment]
> The server linked to ihexds.nist.gov is going through an overhaul and is not available. I suggest downloading the toolkit and using it locally. Bill
> […](#)
> On Dec 10, 2019, at 3:17 AM, atifumarcloud ***@***.***> wrote: Hi Guys, I tried to access these transaction endpoints but these are unable to access, please help? <transaction name="sq.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsregistryb</transaction> <transaction name="sq.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsregistryb</transaction> <transaction name="r.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsregistryb</transaction> <transaction name="r.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsregistryb</transaction> <transaction name="pr.b" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsrepositoryb</transaction> <transaction name="pr.b" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsrepositoryb</transaction> <repository uid="1.19.6.24.109.42.1.5" secure="0">http://ihexds.nist.gov:12080/tf6/services/xdsrepositoryb</repository> <repository uid="1.19.6.24.109.42.1.5" secure="1">https://ihexds.nist.gov:12081/tf6/services/xdsrepositoryb</repository> <home>urn:oid:1.19.6.24.109.42.1.3</home> <transaction name="xcq" secure="0">http://ihexds.nist.gov:12080/tf6/services/rg</transaction> <transaction name="xcq" secure="1">https://ihexds.nist.gov:12081/tf6/services/rg</transaction> <transaction name="xcr" secure="0">http://ihexds.nist.gov:12080/tf6/services/rg</transaction> <transaction name="xcr" secure="1">https://ihexds.nist.gov:12081/tf6/services/rg</transaction> <transaction name="igq" secure="0">http://ihexds.nist.gov:12080/tf6/services/xcaregistry</transaction> <transaction name="igq" secure="1">https://ihexds.nist.gov:12081/tf6/services/xcaregistry</transaction> <transaction name="igr" secure="0">http://ihexds.nist.gov:12080/tf6/services/xcarepository</transaction> <transaction name="igr" secure="1">https://ihexds.nist.gov:12081/tf6/services/xcarepository</transaction> <PidAllocateEndpoint>http://ihexds.nist.gov:12080/xdstools/pidallocate?rest=1</PidAllocateEndpoint> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by atifumarcloud** [comment]
Thank you...
