### ISSUE TITLE
Update reference from IHE FTP site to IHE Google Drive

### ISSUE THREAD

**Issue by lynnfel** [usnistgov/iheos-toolkit2#523]
On this page:  https://github.com/usnistgov/iheos-toolkit2/wiki/Configuring-Toolkit-for-Imaging-Tests#background

... replace ftp://ftp.ihe.net/Connectathon/test_data/RAD-profiles/XDS-I.b_test_data/XDS-ImageCache/ImageCache-20190325.zip

with
https://drive.google.com/drive/folders/1gxn_f-bE_rZU5H06gwwjrZoZtDLafsMg

**Comment by skbhaskarla** [comment]
Done
