### ISSUE TITLE
XDS Provide and Register Document: SOAP Fail: Connection refused

### ISSUE THREAD

**Issue by themnexurst** [usnistgov/iheos-toolkit2#532]
At a XDS Provide and Register Document transaction against the xdstool actor Document Repository the transaction failed.

I am running XDS Tools 7.7.0 on Tomcat 7, my Java version is 1.8.301. 
I did set up local session, adding the Document Repositry & Registry actor, add a Patient ID and provided a single document to this patient (as described in introduction guide http://localhost:8080/xdstools7/site/howto/pnrtosim.html). Uppon that transmission I recive the error:

<html>
<body>

Status: Failure
--
Not using TLS
Not using SAML
Site: begin__rr
Parameters:
...$patientid$: IHEBLUE-2737^^^&1.3.6.1.4.1.21367.13.20.3000&ISO
Starting
------------------------------------------------------------------------------------------------
Test: 2021_10_14_15_41_54_177:SingleDocument-PDF: in begin
------------------------------------------------------------------------------------------------
Status: Fail
Details...
Section: SingleDocument/submit_doc Step: submit_doc
Endpoint: http://localhost:9770/xdstools7/sim/begin__rr/rep/prb
Goals:
SOAP Fault: Connection refused: connect (stepId=submit_doc)
No Message (stepId=submit_doc)
Result was null (stepId=submit_doc)
------------------------------------------------------------------------------------------------
Finished

</body>
</html>

I canot figure out what could possible have gone wrong, but I would have this test to work as I am planning to submit documents with my own Document Source later on.

[fullErrorLog.zip](https://github.com/usnistgov/iheos-toolkit2/files/7346517/fullErrorLog.zip)

**Comment by themnexurst** [comment]
Thank you, this has been the issue and your suggestion fixed it.

May I propose to enter this configuration issue in the Wiki, under Installation, because, unlike the configuration panel is suggesting, one is at this point not actually able to freely set any Toolkit Port.

**Comment by skbhaskarla** [comment]
In the [Configuring Tomcat](https://github.com/usnistgov/iheos-toolkit2/wiki/installing#configuring-tomcat) section of the Installation Wiki page, there was "Just update toolkit.properties with the non-TLS port from Tomcat." Now, I added more useful details based on your feedback.
