### ISSUE TITLE
Toolkit does not seem to save toolkit.properties file

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#540]
I am on my own branch which was made from the develop branch. I have done nothing in the configuration area.

When I bring up the UI to review the Toolkit Properties, the system shows me the right values. However, when I change a value in the UI form, nothing is saved to the backend file. There is no error message in the catalina.out log file.

I tried this using both the toolkit.properties file that is discovered within the war file and also an external version that I use. I pass the path to Tomcat on startup.

This is low priority. You might assign it back to me.

**Comment by mattbackmon** [comment]
I noticed this too—I think this occurs when there is an /etc/toolkit directory.

**Comment by skbhaskarla** [comment]
Thanks for reporting this issue.

I have confirmed that is a bug affecting previous release and develop branch.

Develop branch is fixed.

A new hotfix release will be on the way.
