### ISSUE TITLE
Null pointer exception running XDS Init GW Conformance Test

### ISSUE THREAD

**Issue by alexyz** [usnistgov/iheos-toolkit2#555]
Running the first test (sending ADT) gives an NPE. It's not clear what causes it, as the HL7 port is configured, and the line of code does not look suspicious. GitHub won't let me upload the log.xml, but it's roughly the same as the log text file.
Version: 7.7.2
![adtnpe](https://user-images.githubusercontent.com/905641/178264439-f84b2c2f-0f4f-4079-995c-759525f4b271.png)
[adtnpelog.txt](https://github.com/usnistgov/iheos-toolkit2/files/9083954/adtnpelog.txt)

**Comment by skbhaskarla** [comment]
@alexyz Additional logging is required to see what's going on behind the scenes. 
Please locate your copy of the XDS Toolkit logging.properties, it should be in tomcat\webapps\xdstools\WEB-INF\classes\logging.properties, and change the following log level to FINER as shown below:
### Toolkit wide excluding XDS-I specific packages
gov.nist.level = FINER

Restart toolkit, re-initialize the IG conformance test environment, and upload your Tomcat server log (catalina.out). 
(Other log XML files may be uploaded by renaming the file extension to .txt.)

**Comment by alexyz** [comment]
This is the console output
[adtconsole.txt](https://github.com/usnistgov/iheos-toolkit2/files/9090588/adtconsole.txt)
The ADT transactions worked fine when I tested Document Registry, but doesn't work on IG.

**Comment by alexyz** [comment]
Closing as the test passes on pressing Initialize Test Environment, and only fails when re-run.
