### ISSUE TITLE
TLS error running XDS Init Gateway conformance test

### ISSUE THREAD

**Issue by alexyz** [usnistgov/iheos-toolkit2#556]
Running the IG Test Data step gives a TLS error, even though TLS is not enabled for this test and Toolkit sent the request in the clear. I used Burp Suite to intercept the request, and it shows the Provide and Register request is invalid (zero sized).
![pnrtlserror](https://user-images.githubusercontent.com/905641/178268459-cb25894c-d554-4165-9b54-8737d1f1a2aa.png)
[pnrreqresp.txt](https://github.com/usnistgov/iheos-toolkit2/files/9084133/pnrreqresp.txt)

**Comment by skbhaskarla** [comment]
@alexyz Please post general questions to the IHE XDS Implementors Google group. The project issues page is for confirmed bugs. 
The message says 'or service not available'.  The PnR is sent to a supporting simulator and endpoint should look like the following http://localhost:8080/xdstools/sim/default__community1/rep/prb. Please check Supporting Environment Configuration under Conformance Tests IG Testing Environment. Do you have the necessary simulators endpoints?

**Comment by alexyz** [comment]
I think I understand the problem, similar to the other issue I opened. When I press Initialize Testing Environment, it automatically runs these tests with the simulator parameters and they pass. But re-running any of these tests uses different parameters (my personal XDS Repository above) and the test fails. I will close the issues
