### ISSUE TITLE
Update codes.xml to fix DICOM coding scheme and add to Anatomic regions.

### ISSUE THREAD

**Issue by lynnfel** [usnistgov/iheos-toolkit2#565]
The changes for this issue have been made in this Pull request.
https://github.com/usnistgov/iheos-toolkit2/pull/562

The change has been reviewed and approved by Steve Moore and Lynn Felhofer.

Summary of change:  Adapted and extended the default codes.xml file, based on the discussion between Lynn, John and me [1]. Specifically I

    changed the coding scheme from 1.2.840.10008.2.6.1 to 1.2.840.10008.2.16.4 where appropriate [2] and
    added Anatomic regions with numeric Code Values instead of SNOMED-RT ID as code attributes [3]

**Comment by skbhaskarla** [comment]
Pulled to develop 260be5241ec93aa3a01b55eabf2596e69735fef1.
