### ISSUE TITLE
Relax validation of lid and versionInfo for RegistryObjects

### ISSUE THREAD

**Issue by Thopap** [usnistgov/iheos-toolkit2#598]
When running XDS test 11898 (the first simple testcase), i currenly get a failure on XDS reponse validation:

`SubmissionSet(urn:uuid:eba3dcb3-d5b8-42f8-be71-a47159617eb8): lid attribute empty or missing
XDSRegistryMetadataError
SubmissionSet(urn:uuid:eba3dcb3-d5b8-42f8-be71-a47159617eb8): VersionInfo attribute missing
XDSRegistryMetadataError`

It's true the ebXML state lid and versionInfo as "MUST" for registryObjects. Nethertheless, all XDS samples and specs nether really use this.

In addition, the EVS validator mark result as valid [https://gazelle.ihe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.11.4.8435](https://gazelle.ihe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.11.4.8435) which was complained by the XDS toolkit validator.

Requested change/Fix/improvement:
Relax the validation of lid and versionInfo for at least SubmissionSet's.

**Comment by skbhaskarla** [comment]
Hi @Thopap 
I think this is a reasonable fix but there should be an ITI TF change proposal request (or a post in XDS Google Group) because I just don't know how changing this base-level validation will impact all other existing toolkit users. (The `lid` attribute and `VersionInfo` attribute validation affects SubmissionSets across all tests, not just Test 11898.)

**Comment by Thopap** [comment]
Hello @skbhaskarla,

I have sent a new CP to the CP stackholder in the official process to slighly adjust the definition in section 4.2 of Vol 3 to bring more clarity here.

Best regards,
Thomas

**Comment by Thopap** [comment]
I have raised my proposal as CP to the IHE team, but it was rejected. Even if i still think it might make sense to reduce some unnessary xml waste, but i am also fine with staying with the current state.
