### ISSUE TITLE
XDSToolkit  - Folder Management Support

### ISSUE THREAD

**Issue by mratzenb** [usnistgov/iheos-toolkit2#605]
Hello,

does the XDSToolkit support the [Folder Management](https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html#4.2.2.1.5) as described in Scenario 4: "The Folder is already present. The new submission includes the DocumentEntry and the Association to make the DocumentEntry part of the Folder."

> From the [Folder Management](https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html#4.2.2.1.5) Specification: \
> Scenario 4 – DocumentEntry submitted and added to existing Folder
>
>When a new DocumentEntry is submitted, it can be added to an existing folder. In this case, the SubmissionSet object >will not contain the Folder metadata that correspond to the referenced Folder.

Part of our sample request for adding a new DocumentEntry to an existing folder referenced by its UUID:
```xml
<Association associationType="urn:oasis:names:tc:ebxml-regrep:AssociationType:HasMember"
             id="association_47"
             sourceObject="urn:uuid:81f07851-6bc2-457f-a55e-c77ea65baed7"
             targetObject="document_15"/>
```

Where `sourceObject="urn:uuid:81f07851-6bc2-457f-a55e-c77ea65baed7"` refers to an existing Folder within the XDSToolkit, which is **NOT** part of the current submission set.

With that we receive the following error from the XDSToolkit indicating that the specified UUID already exists, which is expected since the Folder already exists, but we only use the UUID from the folder as reference in the new Association:

```xml
<S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope">
    <S:Header>
        <wsa:Action xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope" s:mustUnderstand="1">urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-bResponse</wsa:Action>
        <wsa:RelatesTo xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:uuid:e34ee510-2100-4703-8250-133d8c30607e</wsa:RelatesTo>
    </S:Header>
    <S:Body>
        <rs:RegistryResponse xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
            <rs:RegistryErrorList>
                <rs:RegistryError codeContext="Submission includes pre-assigned id urn:uuid:81f07851-6bc2-457f-a55e-c77ea65baed7 which is already present in the Registry" errorCode="XDSRegistryMetadataError" location="RegRSim" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
            </rs:RegistryErrorList>
        </rs:RegistryResponse>
    </S:Body>
</S:Envelope>
```

**Comment by skbhaskarla** [comment]
In the XDS Toolkit Conformance Tests for the Registry Actor, Test 12001 tests Adding a new document to an existing folder. I think this is the same as the Scenario 4 you mentioned. I ran this test against a registry simulator and it passed. You can run the test and use the Result Inspector and compare the test tool request with your Document Repository's request.

Looking at your RegistryError response, seems to indicate that you have used the pre-assigned id urn:uuid:81f07851-6bc2-457f-a55e-c77ea65baed7 somewhere else in your metadata as part of your request. Please check to make sure that id is not used anywhere else in your request. It should only be present in the FD-DE association.

**Comment by mratzenb** [comment]
Yes, you are right. It was part of an `ObjectRef` we included in the submission. 

Thanks for the reply. 
I will close this issue.
