### ISSUE TITLE
Site/Actor config - two repositories

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#78]
Originally reported by: **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**

---

At Connectathon when a vendor supports both a Repository and an Integrated Src/Repository they must be configured as two sites in toolkit. Gazelle handles this as a single site.  How should this be handled?

---
- Bitbucket: https://bitbucket.org/iheos/toolkit2/issue/78

**Comment by skbhaskarla** [comment]
This part of the code needs to be updated once we have a new attribute for the repositoryType in the site.xml.

Class gov.nist.toolkit.sitemanagement.TransactionOfferingFactory

Line 95:

// Partial fix Issue 78 (ODDS Issue 98)
					// TODO: may need to retrieve the repositoryType/transactionType flag from the (future) site xml file once it is available. Currently the site xml element in use is just <repository> without any transaction type identifier.
					if (TransactionBean.RepositoryType.ODDS.equals(tb.repositoryType)) {
						tt = TransactionType.ODDS_RETRIEVE;
					} else
						tt = TransactionType.RETRIEVE;

**Comment by iheos** [comment]
This is obsolete.  The new Gazelle system definition loader divides up these conflicting configurations into separate system definitions in toolkit.
