### ISSUE TITLE
Tests failure

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#93]
Originally reported by: **Olivier Herrmann (Bitbucket: [oherrmann](https://bitbucket.org/oherrmann), GitHub: [oherrmann](https://github.com/oherrmann))**

---

I just pull and updated develop branch to the most recent version and when I trigger a maven build I get tests failures. The build itself still successes though. Among the tests that fails I found _OdDocumentConsumerSpec.Run retrieve test:183_ or _OdSpec.setupSpec:41_ or _RetrieveSpec.Run retrieve tests:130_.

You can also find enclosed of the entire build trace in a text file.

---
- Bitbucket: https://bitbucket.org/iheos/toolkit2/issue/93

**Comment by skbhaskarla** [comment]
It-tests worked fine for me with the latest code. Anyone still have problems running integration tests?

**Comment by dazais** [comment]
No issues on my end anymore. I compiled both the develop and master branches from scratch. Both work fine for me and all tests pass.
